### ISSUE TITLE
Plugin "lexxplus_importer" upstream URL ​`https://github.com/LexxPluss/JOSMPlugin/LexxPlussImportPlugin` does not exist (HTTP error 404).

### ISSUE THREAD

**Issue by dreirund** [LexxPluss/JOSMPlugin#19]
*I was recommended [&nearr;&hairsp;here](https://josm.openstreetmap.de/ticket/23817#comment:1) to open this issue:*

Plugin "lexxplus_importer" upstream URL [​https://github.com/LexxPluss/JOSMPlugin/LexxPlussImportPlugin](https://github.com/LexxPluss/JOSMPlugin/LexxPlussImportPlugin) does not exist (HTTP error 404).

[Further commentator](https://josm.openstreetmap.de/ticket/23817#comment:1) did add:

> Looks like they redid their repository (see [​https://github.com/LexxPluss/JOSMPlugin/commits/master/LexxPlussImporter](https://github.com/LexxPluss/JOSMPlugin/commits/master/LexxPlussImporter) ).
> 
> Anyway, the problem is probably [​https://github.com/LexxPluss/JOSMPlugin/blob/master/LexxPlussImporter/build.xml#L16](https://github.com/LexxPluss/JOSMPlugin/blob/master/LexxPlussImporter/build.xml#L16).

Regards!

**Comment by kokosabu** [comment]
@dreirund Thanks for the report. I will check it out.

**Comment by kokosabu** [comment]
@dreirund Completed modification of source code. We will release it soon. I think that will solve the problem.
I will mention again when it is released.

**Comment by kokosabu** [comment]
@dreirund We have released it. I believe it has been resolved.

**Comment by dreirund** [comment]
> *I believe it has been resolved.*

Looks so :-).
