### ISSUE TITLE
拡張子をosnからosmに変更する

### ISSUE THREAD

**Issue by kokosabu** [LexxPluss/JOSMPlugin#2]
保存時の拡張をosnとしているが、osmとして保存して問題ない形式であるため、拡張子osmで保存する。

**Comment by yuichiimamura** [comment]
ソース内の拡張子指定をosmに、addExporterをaddExporterFirstに変更することによりOSM拡張子での保存時に自家製プラグインの動作を優先させることが可能ですが逆にデフォルトのOSM保存処理が使えなくなります。
現時点で画像無しでOSM保存しようとすると自家製プラグインのチェックに引っかかって保存できません。
もちろんPicLayerが存在しない場合には通常のOSM保存処理を実行させることは可能です。
