### ISSUE TITLE
ビルドに失敗する

### ISSUE THREAD

**Issue by kokosabu** [LexxPluss/JOSMPlugin#3]
```
Cannot find .../JOSMPlugin/build-common.xml imported from .../JOSMPlugin/LexxPlussExporter/build.xml
```
というメッセージが表示されビルドに失敗する。
`build-common.xml`のコミット漏れではないか。

**Comment by yuichiimamura** [comment]
プラグインのビルドにはJOSMのビルド環境
 https://josm.openstreetmap.de/osmsvn/applications/editors/josm
をsvnで取得する必要がありますが準備されているでしょうか？
プラグインのソースはpluginsフォルダに展開します。
PicLayerやJOSM本体のクラスも参照するのでこれが無いとビルドできません。

**Comment by kokosabu** [comment]
失礼しました。ビルド環境を準備していませんでした。
無事ビルド通せる事が確認できました。
