### ISSUE TITLE
X, Yをlat, lonに変換する 

### ISSUE THREAD

**Issue by kokosabu** [LexxPluss/JOSMPlugin#9]
**Describe the issue**
OSMを編集し(画像の)X, Y座標を変更した場合、JOSMの表示が変わらない。

**Expected behavior**
X, Yから緯度経度に変換する手段がある

**Definition of Done**
A clear and concise description of what is done.

**Images**

**Additional context**

**Comment by mach0330** [comment]
以降はこちらにコメントを書かせていただきます。
また、便宜上、すでに別の方が実装されているLexxPlussのプラグインをExporterプラグイン、私が作成予定のプラグインを、Importerプラグインと呼ばせて頂きます。

nakaiさんに展開してもらった手順をもとに、私の方でもExporterプラグインの動作確認をさせてわかったのですが、
アウトプットされるtagの情報は、X_image, Y_imageであり、これはメートル単位ではなく、画像のピクセル単位であることがわかりました。
ですので、私が作るImporterプラグインについても、このファイルを読み込まなければいけないため、もともと私が想定していたメートル→緯度経度の変換では対応できず、ピクセル座標→緯度経度への変換を実装する必要があると思います。
また、この変換を行う事前条件として、
- Exporterプラグインでosmに書き出したときに読み込んでいた、PicLayerの画像が読み込まれていること
- 正しい画像が読み込まれていること(Importerプラグイン上では、異なる画像が読み込まれていたとしても気づけない)
という条件が付くと想定しています。
ひとまずはこの方針にて、作業を勧めさせて頂ければと思います。

**Comment by kokosabu** [comment]
ありがとうございます。
OSMの仕様を詳しく理解していないのですが、OSMに画像情報( width, height, くらい? )をExporterプラグインで残せると事前条件が不要になります?

**Comment by mach0330** [comment]
そうですね、画像のwidth, heightに加えて、画像の左上座標に対応する緯度経度、画像の右下座標に対応する緯度経度の情報さえExporterプラグインで残せれば、事前条件は不要になります。
Exporterプラグインのソースコードを、そこまで深く見たわけではないので、実際に対応しているかはわかりませんが、PicLayerの画像は、拡大や縮小だけでなく、回転もできたと思いますので、もし、Exporterプラグインが、PicLayer画像の回転にも対応している場合は、画像の回転角度なども残しておかなければいけないかもしれません。
いずれにせよ、このあたりの、Exporterの改修作業も、私の方で引き受けましょうか？

**Comment by kokosabu** [comment]
引き受けていただけると、ありがたいです。

PicLayerで開いたら、拡大・縮小・回転は行ったことがないので、なんともいえないです。
ただ、PicLayerからいくつか情報を引っ張ってきていたはずなので、拡大・縮小等の操作後の画像情報をもとに緯度経度→ピクセルのX,Yに変換できているのではないかと思います。

**Comment by mach0330** [comment]
承知しました。
ちょっといじってみたところ、Exportするときに、DummyのNodeを作り、その中のTagの情報として上記の必要な情報を残してファイルに書き出すことはできそうなことが分かりましたので、その方針で進めさせて頂きます。

**Comment by mach0330** [comment]
[plugin.zip](https://github.com/LexxPluss/JOSMPlugin/files/6602564/plugin.zip)
Exporter, Importerの両方のプラグインを作成しましたので添付します。
お時間があれば、動作確認をお願いします。
プラグインのインポートの仕方は、前任者がまとめていたreadmeを読んでいただければと思います。
また、importerの使い方ですが、ファイルを読み込むときに、”Lexx Pluss format OSM (*.osm, :.xml)”というフィルタを選んで開いてもらえれば、プラグインのimporterが動きます。

私の方では、
1. JOSMを開く
2. PicLayerで画像を読み込む
3. 画像の拡大、移動、回転を行う
4. 画像に重ねて任意の頂点を置く
5. exporterで保存する
6. 保存したOSMファイルから、手動で緯度経度情報を削除
7. Importerで編集したOSMファイルを読み込む
8. 読み込んだ座標が、4の座標と重なることを確認
という手順で、動作確認を行いました。
これから、簡単なドキュメントをまとめたうえで、branchにpushし、pull requestを出させて頂こうと思っています。
ひとまず、プラグインのみ、先行して提供させて頂きました。
よろしくお願いします。

**Comment by kokosabu** [comment]
以下で実験しました。

1. JOSMを開く
2. PicLayerで画像を読み込む( 過去のosmを流用する為、画像のサイズ変更等は実施しないでおく )
3. 過去のosmファイルを開く( ALL Filesで開いているのでimporterになっていないはず? )
4. exporterで保存する( 画像の情報が登録される )
5. 4で保存したosmファイルをエディタで開き、画像の座標だけのnode, wayを挿入する( 画像のサイズを変更していない為、X,Y座標の関係が変わっていないはず )
6. 編集したosmファイルを開く
7. osmファイルを保存

### 4.で保存したタイミング
![#1](https://user-images.githubusercontent.com/19239/120965744-3f8f9000-c7a0-11eb-90a1-589d60536ddb.png)

### 6.で開いたタイミング
![#2](https://user-images.githubusercontent.com/19239/120965752-428a8080-c7a0-11eb-9e39-6a77bcaa0e07.png)

**Comment by kokosabu** [comment]
X、Y座標だけのデータは上手く表示されていますが、
部屋の外周と同じwayが2重で残って?います。

**Comment by kokosabu** [comment]
最新プラグインで動作確認しました。
意図した形で取り込まれました。
![josm_importer](https://user-images.githubusercontent.com/19239/121113440-07925680-c84d-11eb-8487-191bf8820e10.png)

**Comment by mach0330** [comment]
こちらのミスで古いプラグインをお渡ししてしまったようで、二度手間をおかけしてすみませんでした。
確認頂きありがとうございます。
ドキュメント作成し次第、プルリクエストを出させて頂きます。
